name: log_er
description: "log_er - Powerful & Colorful Logging for Flutter and Dart. Advanced structured logging package with rich formatting, stack traces, and debugging support."
version: 2.0.4
homepage: https://github.com/Developeryilmaz/log_er
repository: https://github.com/Developeryilmaz/log_er
issue_tracker: https://github.com/Developeryilmaz/log_er/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  characters: ^1.4.0
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.0 # Use `test` for Dart packages


linter:
  rules:
    - public_member_api_docs

topics:
  - logging
  - debugging
  - monitoring

funding:
  - https://github.com/sponsors/Developeryilmaz