name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK (Mobile)
        run: flutter build apk || echo "Gradle issue detected. Trying clean build..." && flutter clean && flutter pub get && flutter build apk

      - name: Build iOS (Apple Devices)
        run: flutter build ios --no-codesign -t example/lib/main.dart

      - name: Build macOS (Desktop)
        run: flutter build macos -t example/lib/main.dart

      - name: Build Windows (Desktop)
        run: flutter build windows -t example/lib/main.dart
