name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          cache: true

      - name: Verify Flutter installation
        run: |
          echo "Checking Flutter installation..."
          flutter --version
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build for Mobile and Desktop Only
        run: |
          flutter build apk
          flutter build ios --no-codesign
          flutter build macos
          flutter build windows
